spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jrtp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: swainrinki344@gmail.com
    password: Ajit1234$
    properties:
     mail:
      smtp:
        auth: true
        starttls:
         enable: true
          
   